API_KEY = ""    # used in mindbodyAPI.py
SITE_ID = ""                               # used in mindbodyAPI.py
TEST = "true"                                  # used in mindbodyAPI.py
EMAIL_ID = ""                                   # used in errorMail.py
EMAIL_PASSWORD = ""                             # used in errorMail.py
ICOUNT_COMPANY_ID = ""                   # used in icount.py
ICOUNT_USERNAME = ""                         # used in icount.py
ICOUNT_PASSWORD = ""                      # used in icount.py
MINDBODY_USERNAME = ""                 # used in mindbodyAPI.py, to get userToken
MINDBODY_PASSWORD = ""                  # used in mindbodyAPI.py, to get userToken
